version: "3.9"

services:
  database:
    image: postgres:16
    container_name: po_postgres
    restart: always
    environment:
      POSTGRES_USER: po_postgres
      POSTGRES_PASSWORD: po_postgres
      POSTGRES_DB: po_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # SQL scripts run in alphabetical order on first start
      # https://docs.docker.com/guides/pre-seeding/#pre-seed-the-database-by-bind-mounting-a-sql-script
      - ./database:/docker-entrypoint-initdb.d  

  app:
    build:
      context: ./app
    container_name: po_app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/po_db
    # Optional: auto-reload during development
    # command: ["uv", "run", "--watch", "main.py"]
    volumes:
      - ./app:/app

volumes:
  postgres_data:
